### ISSUE TITLE
Outdated references to legion in remote access page

### ISSUE THREAD

**Issue by krishnakumarg1984** [UCL-RITS/mkdocs-rc-docs#48]
The following content is present in the ssh config file section in the [docs page on remote access](https://www.rc.ucl.ac.uk/docs/Remote_Access/):

```
Host login05
   User ccxxxxx
   HostName login05.external.legion.ucl.ac.uk
   proxyCommand ssh -W login05.external.legion.ucl.ac.uk:22 ccxxxxx@ssh-gateway.ucl.ac.uk
```

The same information is also repeated in the [HowTo page](https://www.rc.ucl.ac.uk/docs/howto/). 

These references to Legion should perhaps be removed.

**Comment by heatherkellyucl** [comment]
@DanielChau128 Instead of

```
qsub -ac allow=L myscript.sh    or      qsub -ac allow=EF myscript.sh
```

do the two commands as separate lines - anything that we're giving as a code block should be fully runnable as stated, so having the `or` in there doesn't allow that.

Something like:
```
qsub -ac allow=L myscript.sh
```
Tells this GPU job to only run on the type L nodes which have Nvidia A100s.

```
qsub -ac allow=EF myscript.sh
```
Tells this GPU job to only run on the type E and F nodes which have Nvidia V100s.

This kind of example where you want feedback on a change before it is fully deployed is a good candidate for talking about branches and pull requests in GitHub.
