### ISSUE TITLE
Suggestion to change documentation organisation

### ISSUE THREAD

**Issue by DanielChau128** [UCL-RITS/mkdocs-rc-docs#60]
I think the following documents would fit more in the "Walkthrough" section:
- Example_Jobscripts
- Interactive_Jobs
- Job_Results
- Remote_Access
- howto

**Comment by heatherkellyucl** [comment]
Those sections are really reference documentation rather than a walkthrough - a walkthrough would be stepping through a specific instance of doing those things, whereas those are the general reference pages for when you want to check on an aspect of those things.

Some people really want more step-by-step examples of a workflow, and those are walkthroughs.
